apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 27.15.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    persistence:
      blueprints:
        volsync:
          - name: blueprints
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      certs:
        volsync:
          - name: certs
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      geoip:
        volsync:
          - name: geo-ip
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      media:
        volsync:
          - name: media
            credentials: s3
            type: restic
            dest:
              enabled: true
            src:
              enabled: true
      templates:
        volsync:
          - name: templates
            credentials: s3
            type: restic
            dest:
              enabled: true
            src:
              enabled: true
    cnpg:
      main:
        mode: standalone
        backups:
          enabled: true
          revision: "3"
          credentials: s3
        recovery:
          method: object_store
          revision: "2"
          credentials: s3
    ingress:
      main:
        enabled: true
        hosts:
          - host: auth.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
          - host: '*.${DOMAIN_0}'
            paths:
              - path: /outpost.goauthentik.io
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-staging
          traefik:
            enabled: true
            entrypoints:
                - websecure
    authentik:
      credentials:
        email: ${NOREPLYADDRESS}
        password: ${AUTHPASS}
      email:
        from: ${NOREPLYADDRESS}
        host: ${SMTPHOST}
        password: ${SMTPPASS}
        port: 465
        timeout: 10
        useSSL: true
        useTLS: true
        username: ${NOREPLYADDRESS}
      general:
        allowUserChangeEmail: true
        allowUserChangeName: true
        allowUserChangeUsername: false
      outposts:
        ldap:
          enabled: false