---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 27.9.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3BUCKETNAME}"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    persistence:
      blueprints:
        volsync:
          - credentials: s3
            dest:
              enabled: true
            name: blueprints
            src:
              enabled: true
            type: restic
      certs:
        volsync:
          - credentials: s3
            dest:
              enabled: true
            name: certs
            src:
              enabled: true
            type: restic
      geoip:
        volsync:
          - credentials: s3
            dest:
              enabled: true
            name: geo-ip
            src:
              enabled: true
            type: restic
      media:
        volsync:
          - credentials: s3
            dest:
              enabled: true
            name: media
            src:
              enabled: true
            type: restic
      templates:
        volsync:
          - credentials: s3
            dest:
              enabled: true
            name: templates
            src:
              enabled: true
            type: restic
    cnpg:
      main:
        backups:
          credentials: s3
          enabled: true
          retentionPolicy: ""
        recovery:
          credentials: s3
          enabled: true
        user: authentik
    ingress:
      main:
        enabled: true
        hosts:
          - host: auth.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
          - host: '*.${DOMAIN_0}'
            paths:
              - path: /outpost.goauthentik.io
                pathType: Prefix
      integrations:
          certManager:
              certificateIssuer: domain-0-le-staging
              enabled: true
          traefik:
              enabled: true
              entrypoints:
                  - websecure
    authentik:
      credentials:
        email: ${NOREPLYADDRESS}
        password: ${AUTHPASS}
      email:
        from: ${NOREPLYADDRESS}
        host: ${SMTPHOST}
        password: ${SMTPPASS}
        port: 465
        timeout: 10
        useSSL: true
        useTLS: true
        username: ${NOREPLYADDRESS}
      general:
        allowUserChangeEmail: true
        allowUserChangeName: true
        allowUserChangeUsername: false
      outposts:
        ldap:
          enabled: false