apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tRthCzUM/7JJ9llQWAAvksSR9pwHabG6VG7jneDg25YGuSYDWcYKlf+DAfFL7LwxoTU7LnGeuHW1LMnU8JrLoDRG5iYpJ7/nktS1XHrFN6wPttFqauu6YB2iBttfN4E0PWD7vByDm5Oete1u1zgBoh9tu7wSnyw3O6ShX0+HdZbNVUlupCfqxrFZm1w9lIAzblXazu965OTnT+jKoNkBMkoR8yX6jm3j2mneLKNoQw9QZ0qrKdn1RrBqpcDEOogUcch4kT2BqQ3QSTRZk7NYBwryJJjj+D254SBzS4wtV+zvKJGf6w9Xb6SVPSCYxLrwPn66vSFYv+TjRHrEt93NLUMCz6Fa1IQlTnWUaoFKTt8ENJlEsayWFRGMYNMP+GWH,iv:ymj1Oqf+8777mWdM19q6zFEblHtgbsKPlGkccj45Fe4=,tag:THuy/wZ+7Yga6ca887sj7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:+BRN4Xq/8obFNoKmCFaKAEZmNL8s3LEz8n5Rm6esuQV1Q2ImV7iRvbhWVCYiOV637+aJAQzOpkpWdimE46UaX2paKNvl+Ge2iBIO84kJ8kjIQn53/Nz/l7CCn93AZJwcZ+axaCaQbx5gzsfh4TYil+9ofRAXOj1ZNyc3xKyKj6Yaj+dmBCc5bhQcqhcFRlKQyPaQJcHaEjUtXMFTkFYqhJRQB4GTAO3QPWFWCfxP4o7O8WAJ6hOwsoPFVcMjjxtCVeL/StJTwb7Mv1zJtw==,iv:ST+PbtAW4B7u92cRaV5h7TD+ZwAY14xP1u6tqrH7nuw=,tag:rI45zdC6BWYe09vDN1NTlg==,type:str]
    known_hosts: ENC[AES256_GCM,data:CweAvZtShrgA7u4gbirR4dVM+kPb4gaiiXsCHfVfT6txJL6CIq2hAM1mLb+RDHG+r32Udyszn4vjod+S4C9Y4e6KNr2HUlOX4/gEm7IJrhje1T/y6+KxrktSdEjx5WY+9vOpSeyNa7yknAgqi7SwlMFWHRQ2bXAZUZMxWafXGorBlfJ3GrA205fNNU1SsU1SWOU9TL5GhjoJLtkVoQ99aQJnxFlks4RHfPDa,iv:cJYao4xd0VpteyViCa+eq8t3svSGRev5MUiRyWS70F0=,tag:TkTy6cPdvenpu+gxzXmDww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14wsxafq0mlu7k8z6nrq8wx2ff4a7deqjs394wx9k0tpr243z9yeshr7477
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTakQxR0pEZGMvcHdOeXdO
            dGVUcWczTlVLTXkrbnFtblk1ZW12RTBSc2trCkx2NTVCYlcrMjJXaGJtMHNySGlU
            a0N1Nk9neTNhQXc2Si9JbzduanBZUjQKLS0tIFF0UVZpTllacCtlOWdFZHAxbDAv
            VzlMNENTbERNdDlmajVmOXZiaERDYjgKF37opTBkaJi/0VDVAvVYVu851VYubX0J
            ZvPgwDpG9Adfy88bDXdG9gwT8cwSsnYxOhShllRGOUWsJtbocskq2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T14:27:07Z"
    mac: ENC[AES256_GCM,data:0Pd8/wvdcLlpjWqCKKJlD0vBi3GAnqImP3G+DJqFL8SjCPjZfn9oFTz2bDU8MF7XizqYZ6wlNQGOcaKZb2vedXWK7X6lFbVznOU1CGZJDVILGnjtYVlv8G5RTfCNWJ2PBfZQMrXtvkwXKkcooA9Lo8b57q0SGomKph6upbDn2HM=,iv:3NjenDgNp6n0rUEo8OfdPLvsNL9j+kQOFpkCZ4VLCjw=,tag:XZ9p6kAoaZ9kynzNOg5qIg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
