apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:w+qQPGV084NOeiFMukA1lWDxUCXJQXhKPVN5epnBX+BZL8IPxraygBYUm94fXM9xnQTQwLns+TUQOjmk4q1dd9LVNM9McjAp7A3MvO30YNV8omspYjpPWAzDR9RTtk/p2WAz2UKcYRLsuJjdE3qNyRwuF7T0ay3tT9o5iTsx2+2WB0fybxdLlpDvhQ+1FzUlH0+3b5YnF1bgYrmVnqTkvW/olJCcLVCERDBRnebfrXQJFe9txju9K49TerME+VEubcwqfp+jvKpD9vp2z7a5pVovrUjMMA19oNnwj5YmuyCGHcU6HUxVUxlIepBVwgS8tBgzFxRPFnOCFXOPRxBjLR/p4ixts7Txv34Co91HzWgXhIG9Lpp/YwL0TqqMgzjG,iv:tWI0vCXr7AWLIG1JqKduAH8gPp600NI6RJLGLsVSmqI=,tag:l/j8pJiYmoMta232fk3YiQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:b8MDN90Kmxb/giFzR7Qq2jhCr2MPQYkSxu7+WfbUx0U6eZ813MtrW3ffurCBimdzLZR0xutXHuezE7wO4gzvgl70WefTaKMLxpFN12DLmmr0jfjOcm45MSIgWtJWi79VyVHYdvYSSD8ciaH3eQQ6jyQv+IbTo3gH6nW7G//Yh2AIPMNFlc+5A9iu6NEultHX9BhJ46CzBQlMz96y377QcGAJwlQrbez78bsOGqXKeQNfU8Xjj+I3xJ86zGF2G6uiY2/kfG38O2dCyGrB3w==,iv:Qd58fliyfH6tUryBaQKlHIgeQ93pdwd8Ryay5br/Bag=,tag:V/VC/kE/Z8b9HAYQYGoFYA==,type:str]
    known_hosts: ENC[AES256_GCM,data:wRvA5h6Eu4376lgfq+DiAD3ctZ0vx4e1C8Jz9qkookDFVw+tWaTITznz9rMrbEFtoM3thYc7RO6cTmE5YEFbYKWrnuqeMD3SycXEHvGtNjETQH+yVd6FPtFQuJ6gyNVzWgcatuSJAGQiSseniDIdDtLwWSh0CzjxifwLPds1fHyHuflxFz6eE9gVZ7iy141rXXxITvhWcHhOj0eFOTk3bOZlUbPuomMK+nNT,iv:Usl3IyDXHMvavR8a1mh9GP0p5RlmpQMr56CfdD/djmk=,tag:G5Q9OPjCr0ClD+xsEKdszA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age13n534wndhqsydga4qanqmuad7gn5m6cy58kxc7g4z9nzg38sn4lqwayhu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QmpZanhRN2FWdzRudFJU
            K3Y0eDdZRHJlNXpLejFEQ3BoTUp0ZDVtUFZrCnpXaDVzRjV2c2Y0aXQweVBQenVT
            VG1BQy9iSS8zSWg3NER3VkYzWk5FVWsKLS0tIGhyOTYwajdPNThZaGh0czhvUlJY
            N3JLbFMvbVZDNlJudjNTTnlpRExnVTgKVd1k3Lwe7P4gpHG8Yq7F8PQR87xVlI7d
            A9rMFVeBe2hBeNnjL5yE6/qAphRGY51hHl2fXWwqDXxm9fbqjMxceA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T13:19:48Z"
    mac: ENC[AES256_GCM,data:GT4wF1TipV3yV/wlEVeq9bHNi/a+cKX+//49elAWUTQOK8qXSZupTZDiuqGcbNI6IWPJpEEBlcapsSjUY/reSETtflqdWNK0Uz+Cw/2Sqe6MW9LJvSqVj61uBe7ZAK8i+1QHjD3JVQeStoHGK3y5Sl3a95i2LvwavIFkWfhY0Mk=,iv:M/zb0pY+IQpGJnSSbQ/VlRZwI0MV1ttksnyTbwf1faA=,tag:7I5nM9NJQxojg1iDTuy2UQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
