apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:raQ4580g4nYqhOSmUO66jhYHU6CXC+HInpsH9L6yzQyAK52VOO8p1dRkvQgw8jXgAFNBt6xTRSmtvL89pdS4oKnSmYB7y7leBhv+r/H7/G3DBxcucC0YUZq/kX8lE1wsj3QQDg6ZK0Tfzo8jnAmDgkDoGrbXqj7qwLM4IeME+usPhDU4xs1MZIG6gCoIZQuXcuhxBQoT6YmRARAr4+yCWG9incIV+OjoH+WGfYGDLEavcYZ+gfV5a+40QHUBs+GYSExlcML5khVwZ1CO4gdYJzhSs4AQbEgyeMDEDChr5rCwHBaZgTBAflKhzG7DElIAqXQYTBksrqmCtE7AH/qdxbnvFjnMgugoopPmidBLmFUnHOoeRcVInGkrYoNqFTYO,iv:ayzP288lt9Sz6QhZwY/gaHE1+YwnKHL0+/ieHj5QUiQ=,tag:8+XPQfI+tDOPlUbZdv899A==,type:str]
    identity.pub: ENC[AES256_GCM,data:5g7Ts6YKt6nz+SDaRhGylfin7xHOaxVd3mMk+1tWnXytl3YyjEpQAAQ7Qti/r1G+iHnQx6k/Nu3yoBNax9E0CnUXlU4q9XsscqkoaFK/xB0UYl8dBhwyy3iYLaHutvNrbXRgT31ebR9oqh8re3mC1oIW5cySEsGybh969UqQ+NLyk2HCSc8iI1RW1ORzj9k6VuFaNZJySLF4sF/YLrt00GOQXWHZtqEtbNj3kI8GH1aZMT7uO7V32KDQLYo0UclkJH25OqEBOPyArdrQ2A==,iv:Tx4GSIkSu4AXWQMMzAeVPE6Lk4YHFzyxUF15IBGcUU8=,tag:GJ+ZFObxT4emOeuypahg8w==,type:str]
    known_hosts: ENC[AES256_GCM,data:hedOSdiC5W3dkPgKb56uDIR6ITHsY9Y/+kl5ht0fSh60vbUnObBcRMckKocnOQ88u6cMZQ8cB4MFdThYoBMq1v4xctekg1Rkm++XDizh/V95wsyubYCAWKjwQ9yWyYOqxxM901oW7CdMajn2hmIwewCBRQcdWVm6QhU9HQtTKQjxbGempmMHRPLIroSfsrNBGZVkFt4ICrC/JNnwdGzcv4DgqrYniKVvEZxA,iv:wQyWSCD8ZrLo+8f77KPMzIoWCYLjDrYl4KTNehiGWUU=,tag:dHZc3HGCjvmjpcZ7KPZQEg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14wsxafq0mlu7k8z6nrq8wx2ff4a7deqjs394wx9k0tpr243z9yeshr7477
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV0xMdFY4aGp0RDVWNEpT
            dnBncFZ5QTE0bXhRRU9xMmtudjNrWW8rcDA4CnJyU0lralFMSVdFSzc1bjBLbVZ2
            b3h3UEtieFpmZHFMVFp6VCt0djFmcG8KLS0tIDlkc1ZaZGVzNk95M3hvbVIrMmNS
            bndydEMwMlBPSTdFQjlEM0Fpbkp0aDQKT87a1X3Mglg0+5NXYWNsN/mfcwVRTxSa
            m73mfuuLzFBwUvA0sgwzEGpwq6N54bfoC5cPUd5AOX/MKHB/D0HHcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T14:14:13Z"
    mac: ENC[AES256_GCM,data:ZJHMUXHMPXAkHWbgFJzx6QkOEW4JUN1ofbXJYa/k4l0n5an8Da6JdliV2gp1751OVyh0X0+1fsUcnF1pNdIz+1HFDbJZsqWayvWKVTcK9tS7DnRHrLzz2+VnAOWlh0/frVxKNqb7aynl78F+UBkYZ82l4XSwFcngV/7NFsxCe8k=,iv:XYrC0VWpAyMgJ8h+3LCXeyWaOimLSuJLHVSV/T0vDiw=,tag:0lst+rVcKntw99hsGXfbjA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
