apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflareddns
  namespace: cloudflareddns
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflareddns
      version: 12.8.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    cloudflareddns:
      user: ${DOMAIN_0_EMAIL}
      api_token: ${DOMAIN_0_CLOUDFLARE_TOKEN}
      host_zone_record:
        - domain: ${DDNS_URL}
          zone: ${DOMAIN_0}
          record: A