apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10h
  path: clusters/main/kubernetes/core/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster