---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: satisfactory
  namespace: satisfactory
spec:
  interval: 24h
  chart:
    spec:
      chart: satisfactory
      version: 12.4.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 24h
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      defaultPodOptions:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values: 
                        - "lemnos"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SATISFACTORYIP}
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                AUTOSAVENUM: 5
                DEBUG: false
                DISABLESEASONALEVENTS: false
                LOG: false
                MAXOBJECTS: 2162688
                MAXPLAYERS: 4
                MAXTICKRATE: 30
                ROOTLESS: false
                SERVERGAMEPORT: "{{ .Values.service.main.ports.main.port }}"
                SERVERIP: "${SATISFACTORYIP}"
                SERVERSTREAMING: true
                SKIPUPDATE: false
                STEAMBETA: false
                TIMEOUT: 30
                VMOVERRIDE: false